/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.Vista;

/**
 *
 * @author Brits
 */
public class PanelEmpleados extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelEmpleados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFechaIngreso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPrimerApellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSegundoApellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSalarioBase = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNumeroFijo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNumeroMovil = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtArea = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(56, 90, 100));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Módulo de administración y mantenimiento de empleados");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 850, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Fecha de ingreso");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 110, 20));

        txtFechaIngreso.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(txtFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 120, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Cédula");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txtCedula.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 130, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nombre");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        txtNombre.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 130, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Primer apellido");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        txtPrimerApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(txtPrimerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 140, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Segundo apellido");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        txtSegundoApellido.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(txtSegundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 130, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Salario base");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        txtSalarioBase.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(txtSalarioBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 110, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Número de teléfono fijo");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        txtNumeroFijo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(txtNumeroFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 70, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Número de teléfono móvil");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        txtNumeroMovil.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtNumeroMovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroMovilActionPerformed(evt);
            }
        });
        add(txtNumeroMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 70, -1));

        jLabel12.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Correo institucional");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 130, -1));

        jLabel18.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(56, 90, 100));
        jLabel18.setText("Datos del empleado");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel19.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(56, 90, 100));
        jLabel19.setText("Información del empleado");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel20.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(56, 90, 100));
        jLabel20.setText("Información de contacto");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/naranja.png"))); // NOI18N
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 60));

        jLabel22.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Área perteneciente");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 130, 20));

        txtArea.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroMovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroMovilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroMovilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaIngreso;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroFijo;
    private javax.swing.JTextField txtNumeroMovil;
    private javax.swing.JTextField txtPrimerApellido;
    private javax.swing.JTextField txtSalarioBase;
    private javax.swing.JTextField txtSegundoApellido;
    // End of variables declaration//GEN-END:variables
}
